// Static corridor reference table, built from SwiftX's real v2 Postman
// collection (per-corridor example payment payloads) plus the SolEng
// Notion checklist's "Corridor specifics" table. `rate` is a plausible
// static FX rate used only by the mock engine — sandbox rates are real,
// but this file has no live credentials, so mock mode needs its own.
//
// `identifierField` is the one thing that actually varies in a way worth
// showing in a demo: India/Pakistan/Bangladesh route on a branch/SWIFT
// code, Nigeria routes on a NIBSS bank code, and the rest route on just
// the bank name + account number.
export const CORRIDORS = [
  {
    code: 'IND',
    name: 'India',
    flag: '🇮🇳',
    currency: 'INR',
    rate: 95.76,
    sourceCurrencies: ['USD', 'AED', 'BHD'],
    identifierField: 'bank_branch_code',
    identifierLabel: 'IFSC Code',
    hasAccountType: true,
    hasValidateAccount: true,
    sample: {
      bank_name: 'HDFC BANK',
      bank_branch_code: 'HDFC0002019',
      beneficiary_name: 'Arun Kumar',
      beneficiary_account_number: '20190100087322',
      beneficiary_account_type: 'savings',
      beneficiary_city: 'Mumbai',
      beneficiary_address: 'MG Road',
      beneficiary_mobile: '8899123456',
      sender_name: 'Arun Kumar Rajendran',
      sender_birthdate: '1993-05-12',
      sender_country: 'ARE',
      sender_city: 'Dubai',
      sender_address: 'Deira Naif Road',
      sender_mobile: '+971554221334',
      sender_relation: 'own',
      sender_identity_doc_type: 'idcard',
      sender_identity_doc: 'P384910223',
      sender_identity_doc_exp: '2027-11-14',
      sender_identity_doc_country: 'ARE',
    },
  },
  {
    code: 'PAK',
    name: 'Pakistan',
    flag: '🇵🇰',
    currency: 'PKR',
    rate: 278.4,
    sourceCurrencies: ['USD', 'AED', 'BHD'],
    identifierField: 'bank_branch_code',
    identifierLabel: 'SWIFT/BIC Code',
    hasAccountType: true,
    hasValidateAccount: false,
    sample: {
      bank_name: 'Allied Bank Limited',
      bank_branch_code: 'ALFHPKKAXXX',
      beneficiary_name: 'Khaja Abdul Rahman',
      beneficiary_account_number: 'PK36ALFH0948001007539903',
      beneficiary_account_type: 'savings',
      beneficiary_city: 'Lahore',
      beneficiary_address: '208 2nd Floor, Mall Road',
      beneficiary_mobile: '+923001234567',
      sender_name: 'Khaja Abdul Saleem',
      sender_birthdate: '1973-01-01',
      sender_country: 'ARE',
      sender_city: 'Dubai',
      sender_address: '208 2nd Floor',
      sender_mobile: '+971552089553',
      sender_relation: 'own',
      sender_identity_doc_type: 'idcard',
      sender_identity_doc: '784197393122037',
      sender_identity_doc_exp: '2026-12-11',
      sender_identity_doc_country: 'ARE',
    },
  },
  {
    code: 'BGD',
    name: 'Bangladesh',
    flag: '🇧🇩',
    currency: 'BDT',
    rate: 122.3,
    sourceCurrencies: ['USD', 'AED', 'BHD'],
    identifierField: 'bank_branch_code',
    identifierLabel: 'Routing Number',
    hasAccountType: true,
    hasValidateAccount: false,
    sample: {
      bank_name: 'Sonali Bank',
      bank_branch_code: '125270607',
      beneficiary_name: 'Khaja Abdul Rahman',
      beneficiary_account_number: '12345678',
      beneficiary_account_type: 'savings',
      beneficiary_city: 'Chittagong',
      beneficiary_address: 'Agrabad, Chittagong',
      beneficiary_mobile: '+8801712345678',
      sender_name: 'Khaja Abdul Saleem',
      sender_birthdate: '1973-01-01',
      sender_country: 'ARE',
      sender_city: 'Dubai',
      sender_address: '208 2nd Floor',
      sender_mobile: '+971552089553',
      sender_relation: 'own',
      sender_identity_doc_type: 'idcard',
      sender_identity_doc: '784197393122037',
      sender_identity_doc_exp: '2026-12-11',
      sender_identity_doc_country: 'ARE',
    },
  },
  {
    code: 'EGY',
    name: 'Egypt',
    flag: '🇪🇬',
    currency: 'EGP',
    rate: 48.6,
    sourceCurrencies: ['USD', 'AED', 'BHD'],
    identifierField: null,
    identifierLabel: null,
    hasAccountType: false,
    hasValidateAccount: false,
    sample: {
      bank_name: 'Unknown',
      beneficiary_name: 'QA Test',
      beneficiary_account_number: '12345678',
      beneficiary_city: 'Cairo',
      beneficiary_address: 'TCR',
      beneficiary_mobile: '+971508674150',
      sender_name: 'QA Test',
      sender_birthdate: '1990-08-22',
      sender_country: 'ARE',
      sender_city: 'Dubai',
      sender_address: 'No Street 1',
      sender_mobile: '+971503248026',
      sender_relation: 'own',
      sender_identity_doc_type: 'idcard',
      sender_identity_doc: 'A987654',
      sender_identity_doc_exp: '2030-12-10',
      sender_identity_doc_country: 'ARE',
    },
  },
  {
    code: 'PHL',
    name: 'Philippines',
    flag: '🇵🇭',
    currency: 'PHP',
    rate: 58.2,
    sourceCurrencies: ['USD', 'AED', 'BHD'],
    identifierField: null,
    identifierLabel: null,
    hasAccountType: true,
    hasValidateAccount: false,
    sample: {
      bank_name: 'BDO Unibank',
      beneficiary_name: 'Ricmi Tarmi',
      beneficiary_account_number: '99345724439934',
      beneficiary_account_type: 'savings',
      beneficiary_city: 'Manila',
      beneficiary_address: 'Makati City, Metro Manila',
      beneficiary_mobile: '+639181234567',
      sender_name: 'Paranthaman Ramakrishnan',
      sender_birthdate: '1970-01-01',
      sender_country: 'ARE',
      sender_city: 'Dubai',
      sender_address: '221B Baker Street',
      sender_mobile: '+971503248026',
      sender_relation: 'brother',
      sender_identity_doc_type: 'idcard',
      sender_identity_doc: 'A987654',
      sender_identity_doc_exp: '2038-01-01',
      sender_identity_doc_country: 'ARE',
    },
  },
  {
    code: 'VNM',
    name: 'Vietnam',
    flag: '🇻🇳',
    currency: 'VND',
    rate: 25400,
    sourceCurrencies: ['USD', 'AED', 'BHD'],
    identifierField: null,
    identifierLabel: null,
    hasAccountType: false,
    hasValidateAccount: false,
    sample: {
      bank_name: 'Unknown',
      beneficiary_name: 'QA Test',
      beneficiary_account_number: '12345678',
      beneficiary_city: 'Saigon',
      beneficiary_address: 'TCR',
      beneficiary_mobile: '+971508674150',
      sender_name: 'QA Test',
      sender_birthdate: '1990-08-22',
      sender_country: 'ARE',
      sender_city: 'Dubai',
      sender_address: 'No Street 1',
      sender_mobile: '+971503248026',
      sender_relation: 'own',
      sender_identity_doc_type: 'other',
      sender_identity_doc: 'A987654',
      sender_identity_doc_exp: '2030-12-10',
      sender_identity_doc_country: 'ARE',
    },
  },
  {
    code: 'NGA',
    name: 'Nigeria',
    flag: '🇳🇬',
    currency: 'NGN',
    rate: 1530,
    // The official OpenAPI example for Nigeria uses AED as the source currency —
    // an earlier note claiming "USD only" was wrong; the schema has no per-corridor restriction.
    sourceCurrencies: ['USD', 'AED', 'BHD'],
    identifierField: 'bank_code',
    identifierLabel: 'NIBSS Bank Code',
    hasAccountType: false,
    hasValidateAccount: false,
    sample: {
      bank_name: 'Guaranty Trust Bank',
      bank_code: '000001',
      beneficiary_name: 'Ngozi Obi',
      beneficiary_account_number: '2345678901',
      beneficiary_city: 'Port Harcourt',
      beneficiary_address: '42 Aba Road',
      beneficiary_mobile: '+2348031122334',
      sender_name: 'Chinedu Obi',
      sender_birthdate: '1987-09-11',
      sender_country: 'ARE',
      sender_city: 'Abu Dhabi',
      sender_address: 'Electra Street, Abu Dhabi',
      sender_mobile: '+971503456789',
      sender_relation: 'wife',
      sender_identity_doc_type: 'idcard',
      sender_identity_doc: '784234567890123',
      sender_identity_doc_exp: '2032-08-21',
      sender_identity_doc_country: 'ARE',
    },
  },
];

export function getCorridor(code) {
  const corridor = CORRIDORS.find((c) => c.code === code);
  if (!corridor) {
    const err = new Error(`Unknown corridor ${code}`);
    err.status = 400;
    throw err;
  }
  return corridor;
}
